### ISSUE TITLE
Not showing conversions

### ISSUE THREAD

**Issue by macrospecter** [giovannicoppola/alfred-convert#1]
Hi there. I tried out another of your workflows, and seem to have run into a problem. I can't get Convert to work, even after feeding an API in. I've pasted below the contents of the debugging report when I tried to convert 300ml to another unit by typing "conv 300ml..." Any idea what my problem might be?

[14:21:40.355] Convert[Script Filter] Queuing argument '300'
[14:21:40.430] Convert[Script Filter] Script with argv '300' finished
[14:21:40.431] ERROR: Convert[Script Filter] Code 1: .
http_proxy=
https_proxy=
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by giovannicoppola** [comment]
yes, please check the solution here:
https://www.alfredforum.com/topic/20088-one-workflow-problem-led-to-another-cal/?do=findComment&comment=103767

**Comment by macrospecter** [comment]
I'm sorry, that didn't work for me. I got the following error: "xcode-select: error: command line tools are already installed, use "Software Update" to install updates."

**Comment by giovannicoppola** [comment]
how did you install python? Sometimes things get confused if there are multiple python installations. what do you get if you try `which -a python` in terminal?

**Comment by macrospecter** [comment]
It's saying Python not found, in response to that command. I have, however, installed Python 3.11 using both the package installer and Homebrew. I got messages from both the installer popup window and Terminal, respectively, that the installation was complete. I'm not a coder, though, and so don't use it myself--so I can't say if it's working.

**Comment by macrospecter** [comment]
I will say, though, that the issue seems to have changed. I'm now, rather than just not getting any feedback at all from the query, getting an error message. Here's the debugger report:

08:40:34 workflow.py:2093 DEBUG    ---------- Convert (4.0.1) ----------
08:40:34 convert.py:647 DEBUG    query : 100 miles to kilometers
08:40:34 workflow.py:1483 DEBUG    reading settings from /Users/erinmiller/Library/Application Support/Alfred/Workflow Data/alfred-convert-GC/settings.json
08:40:34 workflow.py:2285 DEBUG    last run version: 4.0.1
08:40:34 convert.py:104 DEBUG    version=4.0.1, last_version=4.0.1
08:40:34 background.py:233 DEBUG    [update] command cached: /Users/erinmiller/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/alfred-convert-GC/update.argcache
08:40:34 background.py:237 DEBUG    [update] passing job to background runner: ['/usr/local/bin/python3', '-m', 'workflow.background', 'update']
.
08:40:34 workflow.py:2093 DEBUG    ---------- Convert (4.0.1) ----------
08:40:34 background.py:243 DEBUG    [update] background job started
08:40:34 convert.py:382 DEBUG    [parser] quantity=100.0, tail=miles to kilometers
08:40:34 convert.py:484 DEBUG    [parser] from_unit=miles
08:40:34 convert.py:488 DEBUG    [parser] to_unit=to
08:40:34 convert.py:563 CRITICAL invalid query (100 miles to kilometers): More than 2 units specified
08:40:34 convert.py:626 DEBUG    finished
08:40:34 workflow.py:2314 DEBUG    set last run version: 4.0.1
08:40:34 workflow.py:2136 DEBUG    ---------- finished in 0.127s ----------

**Comment by giovannicoppola** [comment]
now it's running correctly. It's interpreting `to` as a unit, just enter `100 miles km`

**Comment by macrospecter** [comment]
Oh, of course. Thank you!

**Comment by macrospecter** [comment]
There does seem to be one last issue, when I try to convert currencies: I'm getting an error that I need to set the APP_KEY variable. However, I did get an App ID from Open Exchange Rates and pasted that into the configuration field. Do you happen to know if the App ID is different from the API key? I couldn't find info about it anywhere on their website.

**Comment by giovannicoppola** [comment]
App ID should work. what is the debugger message?

**Comment by macrospecter** [comment]
09:30:22 workflow.py:2093 DEBUG    ---------- Convert (4.0.1) ----------
09:30:22 background.py:243 DEBUG    [update] background job started
09:30:22 convert.py:382 DEBUG    [parser] quantity=100.0, tail=USD yen
09:30:22 convert.py:484 DEBUG    [parser] from_unit=USD
09:30:22 convert.py:488 DEBUG    [parser] to_unit=yen
09:30:22 convert.py:73 ERROR    [parser] unit USD is a fiat currency, but OpenExchangeRates.org API key isn't set

And it says in the Alfred window, as two dropdown options below the window: "Fetching exchange rates (Exchange rates will be momentarily possible)" and "Set APP_KEY to convert this currency." 

I tried setting API_KEY in three ways: as the API Key in the main configuration window (the one that pops up when you click on the "[x]" icon on the workflow page), as a hand-entered APP_KEY for an environmental variable, and as the default for the API_KEY configuration variable. Not all at once--I tried these separately.

**Comment by giovannicoppola** [comment]
setting the API in `Configure Workflow...` should work. probably unrelated, but but could you try `EUR` or the yen abbreviation `jpy`?

**Comment by macrospecter** [comment]
I tried EUR and JPY; they were recognized (a brief "unrecognized currency" message flashed but disappeared), but I get the same error messages for them.

**Comment by giovannicoppola** [comment]
@macrospecter just checking if this is solved for you... I just checked the currency conversion and it still works 
<img width="1067" alt="image" src="https://github.com/giovannicoppola/alfred-convert/assets/5774411/802cf966-70d3-4841-99d4-501d997df0f0">

**Comment by macrospecter** [comment]
It didn't work initially, but for some reason it does now! Thank you.

**Comment by SALMANKHAN222coll** [comment]
https://github.com/giovannicoppola/alfred-convert/issues/7#issue-2188755552
