### ISSUE TITLE
Shortcut for Celsius <-> fahrenheit conversion

### ISSUE THREAD

**Issue by johntdyer** [giovannicoppola/alfred-convert#3]
because I'm to lazy to do the math in my head it would be nice if Fahrenheit to Celsius was more of a first class function... I've only been able to get it to work by doing 

```
conv 80 fahrenheit celsius
```
which is a lot of letters :  Also its worth mentioning that its also case sensitive, `conv 80 Fahrenheit Celsius` wont work.  IT would be nice if were something more along the lines of 

```
conv 80c to f
```

**Comment by fmeilleur** [comment]
If you feel adventurous, you can edit the `default_en.txt` file and change
`degC = kelvin; offset: 273.15 = celsius` 
to 
`degC = kelvin; offset: 273.15 = celsius = C` 
and so on...

Doing so will enable you to type `conv 80 C F` and get the result you want.

**Comment by giovannicoppola** [comment]
@johntdyer you might want to check the new [Unit Converter](https://alfred.app/workflows/alfredapp/unit-converter/) from the Alfred team, it's fast and a bit more flexible. 
<img width="898" alt="image" src="https://github.com/giovannicoppola/alfred-convert/assets/5774411/0ef39ee2-10b4-4982-b7ce-502ba92e415b">
